---
- name: Ansible Deployment on target machines present in inventory file. 
  hosts: all
  tasks:
    - name: Stop Docker container
      docker_container: 
        name: spe-calc
        state: stopped
        
    - name: Remove Docker container
      docker_container: 
        name: spe-calc
        state: absent 
        
    - name: Remove Docker image
      docker_image:
        state: absent
        name: aadarsh96/spe-calc
        tag: latest 
    
    - name: Pull spe-calc devops image
      docker_image:
        name: aadarsh96/spe-calc:latest
        source: pull
        
    - name: deploy spe-calc docker container
      docker_container:
        image: aadarsh96/spe-calc:latest
        name: spe-calc
        state: started
        auto_remove: true
        ports:
          - "3221:80"
...
